query ($owner: String!, $name: String!, $prNumber: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $prNumber) {
      headRef {
        target {
          ... on Commit {
            checkSuites(first: 10, filterBy: {appId: 15368}) {
              nodes {
                workflowRun {
                  databaseId
                  pendingDeploymentRequests(first: 100) {
                    totalCount
                    nodes {
                      environment {
                        databaseId
                      }
                    }
                  }
                }
                checkRuns(first: 100, filterBy: {checkType: LATEST, status: WAITING}) {
                  nodes {
                    deployment {
                      environment
                      databaseId
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
