name: deployment
on:
  pull_request:
jobs:
  deploy-staging:
    name: 'Deploy ${{ matrix.env }}'
    strategy:
      matrix:
        env:
          - staging-2
          - staging-3
    runs-on: ubuntu-slim
    environment: ${{ matrix.env }}
    concurrency:
      group: ${{ matrix.env }}-deployment
      cancel-in-progress: true
    steps:
      - run: echo "deployed $_env"
        env:
          _env: ${{ matrix.env }}
  deploy-production:
    name: 'Deploy production'
    runs-on: ubuntu-slim
    environment: production
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    needs:
      - deploy-staging
    steps:
      - run: echo deployed
