name: deployment
on:
  workflow_dispatch:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    steps:
      - run: echo OK
