on:
  issue_comment:
    types: [created]
jobs:
  confirm-diff:
    name: confirm diff
    runs-on: ubuntu-latest
    steps:
      -
        id: determine_pr_ref
        name: determine ref
        run: |
          cat ${GITHUB_EVENT_PATH}
          pr_url=$(jq -r .issue.pull_request.url < ${GITHUB_EVENT_PATH})
          if [[ "$pr_url" == "" ]]; then
            exit 0
          fi
          head_ref="$(curl -sS \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${pr_url} | \
            jq -r .head.ref)"
          echo $head_ref
        outputs:
          pr_head_ref:
      -
        uses: actions/checkout@v1
        with:
          ref: ${{ steps.determine_pr_ref.outputs.pr_head_ref }}
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        run: yarn install --frozen-lockfile
      -
        name: tell user that PR requires check
        run: |
          body="$(jq -r .comment.body < ${GITHUB_EVENT_PATH})"
          if [[ "$body" != "accept diff" ]]; then
            exit 0
          fi

          yarn test -u
          git add -u test/
          export GIT_COMMITTER_NAME="${GITHUB_ACTOR}"
          export GIT_COMMITTER_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com"
          export GIT_AUTHOR_NAME="${GIT_COMMITTER_NAME}"
          export GIT_AUTHOR_EMAIL="${GIT_COMMITTER_EMAIL}"
          git commit -m 'update snapshot'
          git push origin ${{ steps.determine_pr_ref.outputs.pr_head_ref }}
