on:
  issue_comment:
    types: [created]
jobs:
  confirm-diff:
    name: confirm diff
    runs-on: ubuntu-latest
    steps:
      -
        name: tell user that PR requires check
        run: |
          is_pr="$(jq -r 'if .issue.pull_request then true else false end' < ${GITHUB_EVENT_PATH})"
          if [[ "$is_pr" != "true" ]]; then
            cat ${GITHUB_EVENT_PATH}
            exit 0
          fi
          body="$(jq -r .comment.body < ${GITHUB_EVENT_PATH})"
          if [[ "$body" != "accept diff" ]]; then
            exit 0
          fi
          statuses_url=$(jq -r .ssue.pull_request.statuses_url < ${GITHUB_EVENT_PATH})
          payload="$(echo '{"state":"success","context":"check-diff"}' | jq .)"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${payload}" \
            ${statuses_url}
