on:
  issue_comment:
    types: [created]
jobs:
  confirm-diff:
    name: confirm diff
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        run: yarn install --frozen-lockfile
      -
        name: tell user that PR requires check
        run: |
          cat ${GITHUB_EVENT_PATH}
          is_pr="$(jq -r 'if .issue.pull_request then true else false end' < ${GITHUB_EVENT_PATH})"
          if [[ "$is_pr" != "true" ]]; then
            exit 0
          fi
          body="$(jq -r .comment.body < ${GITHUB_EVENT_PATH})"
          if [[ "$body" != "accept diff" ]]; then
            exit 0
          fi

          yarn test -u
          git add -u test/
          export GIT_COMMITTER_NAME="${GITHUB_ACTOR}"
          export GIT_COMMITTER_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com"
          export GIT_AUTHOR_NAME="${GIT_COMMITTER_NAME}"
          export GIT_AUTHOR_EMAIL="${GIT_COMMITTER_EMAIL}"
          git commit -m 'update snapshot'
          git push origin HEAD
