name: test
on: [pull_request]
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      -
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: '12.x'
      -
        run: yarn install --frozen-lockfile
      -
        run: yarn workspace cdk ci || true
      -
        name: check snapshot test results
        run: |
          failed_tests="$(jq '.numFailedTests' < cdk/results.json)"
          if [[ $failed_tests = 0 ]]; then
            exit 0
          fi
          unmatched_snapshots="$(jq '.snapshot.unmatched' < cdk/results.json)"
          if [[ $unmatched_snapshots = 0 ]]; then
            exit 1
          fi

          statuses_url=$(jq -r .pull_request.statuses_url < ${GITHUB_EVENT_PATH})
          status_payload="$(echo '{"state":"failure","context":"cdk/snapshot"}' | jq .)"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${status_payload}" \
            ${statuses_url}

          comments_url=$(jq -r .pull_request.comments_url < ${GITHUB_EVENT_PATH})
          comment_payload="$(echo '{}' | jq --arg body '@${{ github.actor }} your latest change introduced snapshot change. please confirm diff.' '.body = $body')"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${comment_payload}" \
            ${comments_url}
