on: [pull_request]
jobs:
  check-diff:
    name: check diff
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout
      -
        uses: actions/setup-node
        with:
          node-version: '12.x'
      -
        run: yarn install --frozen-lockfile
      -
        run: yarn test
