---

name: pull request closed
on:
  pull_request:
    types:
      - closed
jobs:
  when-unmerged:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          base_ref: ${{ github.base_ref }}
          head_ref: ${{ github.head_ref }}
        run: |
          echo "base_ref=${base_ref}"
          echo "head_ref=${head_ref}"
