---

name: pull request closed
on:
  pull_request:
    types:
      - closed
jobs:
  when-unmerged:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git push --delete origin $_head
        env:
          _head: ${{ github.head_ref }}
