name: test
on: [pull_request]
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        run: yarn install --frozen-lockfile
      -
        run: yarn ci || true
      -
        name: check snapshot test results
        run: |
          failed_tests="$(jq '.numFailedTests' < results.json)"
          if [[ $failed_tests = 0 ]]; then
            exit 0
          fi
          unmatched_snapshots="$(jq '.snapshot.unmatched' < results.json)"
          if [[ $unmatched_snapshots = 0 ]]; then
            exit 1
          fi

          statuses_url=$(jq -r .pull_request.statuses_url < ${GITHUB_EVENT_PATH})
          status_payload="$(echo '{"state":"failure","context":"cdk/snapshot"}' | jq .)"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${status_payload}" \
            ${statuses_url}

          body="@${GITHUB_ACTOR} your latest change introduced snapshot change. please confirm diff.\n<details><summary>result</summary>"
          message="$(jq -r '.testResults[].message' < results.json)"
          body="${body}\n```\n${message}\n```</details>"
          comments_url=$(jq -r .pull_request.comments_url < ${GITHUB_EVENT_PATH})
          comment_payload="$(echo '{}' | jq --arg body "$body" '.body = $body')"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${comment_payload}" \
            ${comments_url}
