---

name: pull request closed
on:
  pull_request:
    types:
      - closed
jobs:
  delete-unmerged:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: |
          git push --delete origin $_head
        env:
          _head: ${{ github.head_ref }}
  cancel-abandoned-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const variables = {
              owner: context.repo.owner,
              name: context.repo.name,
              prNumber: context.event.number,
            };
            const query = `
              query ($owner: String!, $name: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $name) {
                  pullRequest(number: $prNumber) {
                    headRef {
                      target {
                        ... on Commit {
                          checkSuites(first: 10, filterBy: {appId: 15368}) {
                            nodes {
                              app {
                                databaseId
                                slug
                              }
                              checkRuns(first: 10, filterBy: {checkType: LATEST, status: WAITING}) {
                                nodes {
                                  name
                                  deployment {
                                    environment
                                    databaseId
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query, variables);
            console.log(JSON.stringify(result, null, 2));
