on: [pull_request]
jobs:
  check-diff:
    name: check diff
    runs-on: ubuntu-latest
    steps:
      -
        name: tell user that PR requires check
        run: |
          statuses_url=$(jq -r .pull_request.statuses_url < ${GITHUB_EVENT_PATH})
          payload="$(echo '{"state":"failure","context":"check-diff"}' | jq .)"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${payload}" \
            ${statuses_url}
      -
        name: report diff
        run: |
          comments_url=$(jq -r .pull_request.comments_url < ${GITHUB_EVENT_PATH})
          comment_payload="$(echo '{}' | jq --arg body '@${{ github.actor }} hi i am a robot' '.body = $body')"
          curl -sS -XPOST \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            -d "${comment_payload}" \
            ${comments_url}
